# Generated by Django 5.0.2 on 2024-02-08 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Qusetion",
            new_name="Question",
        ),
    ]
