# Generated by Django 4.1 on 2024-02-09 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_qusetion_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_data',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 12, 10, 9, 271581, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
